pm enable com.coloros.bootreg
pm enable com.android.stk
pm enable com.coloros.childrenspace
pm enable com.iflytek.speechsuite
pm enable com.coloros.remoteguardservice
pm enable com.coloros.healthcheck
pm enable com.coloros.healthservice
pm enable com.coloros.operationManual
pm enable com.coloros.deepthinker
pm enable com.oppo.bttestmode
pm enable com.oppo.wifitest
pm enable com.oppo.nhs
pm enable com.google.ar.core
pm enable com.google.android.accessibility.soundamplifier
pm enable com.opos.ads
pm enable com.coloros.sau
pm enable com.coloros.sauhelper
pm enable com.oppo.ota
pm enable com.oppo.oppopowermonitor
pm enable com.coloros.oppoguardelf/com.coloros.powermanager.fuelgaue.GuardElfAIDLService
pm enable com.coloros.oppoguardelf/com.coloros.oppoguardelf.OplusGuardElfService
pm enable com.coloros.codebook
pm enable com.coloros.securepay
pm enable com.coloros.securitykeyboard
pm enable com.coloros.securityguard
pm enable com.coloros.gamespace
pm enable com.coloros.gamespaceui
pm enable com.nearme.statistics.rom
pm enable com.oplus.onetrace
pm enable com.oplus.crashbox
pm enable com.oplus.postmanservice
pm enable com.heytap.habit.analysis
pm enable com.google.mainline.telemetry
pm enable com.coloros.logkit
rm -rf /sdcard/Android/CMod